### ISSUE TITLE
如何在多个activity中保持ble的连接状态

### ISSUE THREAD

**Issue by AndyGu** [JoeSteven/RxBle#1]
现在在onPause中会调用
mOperator.disconnect();
mOperator.stopScan();
导致activity跳转后就断连了，需要在新页面再次建立连接，而且如果observeConnectionStateChanges监听了connection的状态，里面的断连回调也会触发
而如果不断连，再次connect就会报“Already connected to device with MAC address”的BleAlreadyConnectedException
请问下在多Activity情况下，有没有什么好办法处理？

**Comment by JoeSteven** [comment]
你好，不好意思，最近比较忙没来得及看github。
我理解你的问题是想要在多Activity场景下操作同一蓝牙设备。
sample 中在pause里面去断连只是一种示例写法，因为rx是基于观察者模式，这样是为了避免内存泄露。
多Activity 的场景， 你完全可以独立出一个类似mvp 中的 presenter 的 helper 对象，activity只和helper交互，helper去操作真正的蓝牙接口。
当activity销毁的时候通过helper去反注册解决内存泄露的问题就可以了，不需要断连。
希望能帮助到你

**Comment by JoeSteven** [comment]
haven't receive respond for a long time ,assume you already solved this issue
